
-- Enable necessary extensions (if needed, usually public is default)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Offices / Agencies Table
CREATE TABLE IF NOT EXISTS offices (
    office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Reference Locations Table (Provinces/Cities/Municipalities)
CREATE TABLE IF NOT EXISTS ref_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_huc TEXT NOT NULL,
    city_mun TEXT -- Nullable for Province level entries
);

-- 3. Users Table (Manual Auth, not Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL, -- Bcrypt hash
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Scanner', 'EventManager')),
    position TEXT,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    office_id BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    venue TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL, -- Can be same as start_date
    event_serial TEXT,
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Ongoing', 'Completed', 'Cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    organize_by BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    has_accommodation BOOLEAN DEFAULT FALSE,
    registration_open BOOLEAN DEFAULT TRUE,
    session TEXT NOT NULL DEFAULT 'All_Day' CHECK (session IN ('AM', 'PM', 'All_Day')),
    days_accommodation SMALLINT,
    dates_with_accom DATE[],
    food_inclusion TEXT[],
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    delete_reason TEXT
);

ALTER TABLE events
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS delete_reason TEXT;

CREATE INDEX IF NOT EXISTS events_active_idx
    ON events(start_date DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS events_deleted_idx
    ON events(deleted_at DESC)
    WHERE deleted_at IS NOT NULL;

-- 5. Participants Table
CREATE TABLE IF NOT EXISTS participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_code TEXT NOT NULL UNIQUE, -- Used for QR
    full_name TEXT NOT NULL,
    email TEXT,
    mobile_no TEXT,
    gender TEXT,
    position TEXT,
    office TEXT, -- Text representation of office/LGU if not linked strictly
    location_id BIGINT REFERENCES ref_locations(location_id) ON DELETE SET NULL,
    age_group TEXT,
    pwd TEXT DEFAULT 'No',
    indigenous_people TEXT DEFAULT 'No',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Event Participants Junction Table (Registration)
CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    registration_status TEXT NOT NULL DEFAULT 'Registered' CHECK (registration_status IN ('Registered', 'Cancelled')),
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    accommodation_pax INT DEFAULT 0 CHECK (accommodation_pax >= 0),
    role TEXT NOT NULL DEFAULT 'Delegate' CHECK (role IN ('Delegate', 'Speaker', 'Secretariat', 'Guest', 'VIP')),
    needs_accommodation BOOLEAN DEFAULT FALSE,
    accept_photo_video BOOLEAN NOT NULL DEFAULT FALSE,
    store_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    date_accommodation DATE[],
    ca_serial_no INT NULL,
    ca_issued_at TIMESTAMP WITH TIME ZONE NULL,
    UNIQUE(event_id, participant_id)
);

-- Ensure CA serial numbers are unique per event (skips NULL rows that haven't been issued yet).
CREATE UNIQUE INDEX IF NOT EXISTS event_participants_ca_serial_unique
    ON event_participants(event_id, ca_serial_no)
    WHERE ca_serial_no IS NOT NULL;

-- Assigns the next sequential CA serial numbers to the given participants for an event.
-- Skips participants that already have a serial. Refuses to assign when the event has no event_serial.
-- Uses a transaction-level advisory lock keyed by event_id to make concurrent calls safe.
CREATE OR REPLACE FUNCTION assign_ca_serials(
    p_event_id BIGINT,
    p_participant_ids BIGINT[]
)
RETURNS TABLE(out_participant_id BIGINT, out_ca_serial_no INT) AS $$
DECLARE
    v_event_serial TEXT;
    v_next_no INT;
    v_participant_id BIGINT;
BEGIN
    SELECT event_serial INTO v_event_serial FROM events WHERE event_id = p_event_id;

    IF v_event_serial IS NULL OR btrim(v_event_serial) = '' THEN
        RAISE EXCEPTION 'Event % does not use reference coding', p_event_id
            USING ERRCODE = 'check_violation';
    END IF;

    PERFORM pg_advisory_xact_lock(p_event_id);

    SELECT COALESCE(MAX(ep.ca_serial_no), 0) INTO v_next_no
    FROM event_participants ep
    WHERE ep.event_id = p_event_id;

    FOREACH v_participant_id IN ARRAY p_participant_ids LOOP
        UPDATE event_participants ep
        SET ca_serial_no = v_next_no + 1,
            ca_issued_at = NOW()
        WHERE ep.event_id = p_event_id
          AND ep.participant_id = v_participant_id
          AND ep.ca_serial_no IS NULL;

        IF FOUND THEN
            v_next_no := v_next_no + 1;
        END IF;
    END LOOP;

    RETURN QUERY
    SELECT ep.participant_id::BIGINT, ep.ca_serial_no::INT
    FROM event_participants ep
    WHERE ep.event_id = p_event_id
      AND ep.participant_id = ANY(p_participant_ids);
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION events_set_status_from_dates()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.status = 'Cancelled' THEN
        RETURN NEW;
    END IF;

    IF CURRENT_DATE < NEW.start_date THEN
        NEW.status := 'Scheduled';
    ELSIF CURRENT_DATE > NEW.end_date THEN
        NEW.status := 'Completed';
    ELSE
        NEW.status := 'Ongoing';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_set_status_from_dates_trg ON events;

CREATE TRIGGER events_set_status_from_dates_trg
BEFORE INSERT OR UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION events_set_status_from_dates();

-- 7. Attendance Logs Table
CREATE TABLE IF NOT EXISTS attendance_logs (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL, -- Who scanned it
    attendance_date DATE NOT NULL,
    scan_time TIMESTAMP WITH TIME ZONE NOT NULL,
    action_session TEXT NOT NULL CHECK (action_session IN ('AM', 'PM')),
    scan_status TEXT NOT NULL DEFAULT 'Valid' CHECK (scan_status IN ('Valid', 'Duplicate', 'Invalid', 'Late')),
    scanner_device TEXT,
    remarks TEXT
);

-- Enable Realtime for specific tables (Required for Supabase Realtime client)
alter publication supabase_realtime add table events;
alter publication supabase_realtime add table event_participants;
alter publication supabase_realtime add table attendance_logs;
