
-- Enable necessary extensions (if needed, usually public is default)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Offices / Agencies Table
CREATE TABLE IF NOT EXISTS offices (
    office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Reference Locations Table (Provinces/Cities/Municipalities)
CREATE TABLE IF NOT EXISTS ref_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_huc TEXT NOT NULL,
    city_mun TEXT -- Nullable for Province level entries
);

-- 3. Users Table (Manual Auth, not Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL, -- Bcrypt hash
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Scanner', 'EventManager')),
    position TEXT,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    office_id BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    venue TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL, -- Can be same as start_date
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Ongoing', 'Completed', 'Cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    organize_by BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    has_accommodation BOOLEAN DEFAULT FALSE,
    registration_open BOOLEAN DEFAULT TRUE,
    session TEXT NOT NULL DEFAULT 'All_Day' CHECK (session IN ('AM', 'PM', 'All_Day')),
    days_accommodation SMALLINT,
    dates_with_accom DATE[]
);

-- 5. Participants Table
CREATE TABLE IF NOT EXISTS participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_code TEXT NOT NULL UNIQUE, -- Used for QR
    full_name TEXT NOT NULL,
    email TEXT,
    mobile_no TEXT,
    gender TEXT,
    position TEXT,
    office TEXT, -- Text representation of office/LGU if not linked strictly
    location_id BIGINT REFERENCES ref_locations(location_id) ON DELETE SET NULL,
    age_group TEXT,
    pwd TEXT DEFAULT 'No',
    indigenous_people TEXT DEFAULT 'No',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Event Participants Junction Table (Registration)
CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    registration_status TEXT NOT NULL DEFAULT 'Registered' CHECK (registration_status IN ('Registered', 'Cancelled')),
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    accommodation_pax INT DEFAULT 0 CHECK (accommodation_pax >= 0),
    role TEXT NOT NULL DEFAULT 'Delegate' CHECK (role IN ('Delegate', 'Speaker', 'Secretariat', 'Guest', 'VIP')),
    needs_accommodation BOOLEAN DEFAULT FALSE,
    accept_photo_video BOOLEAN NOT NULL DEFAULT FALSE,
    store_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    date_accommodation DATE[],
    UNIQUE(event_id, participant_id)
);

CREATE OR REPLACE FUNCTION events_set_status_from_dates()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'Cancelled' THEN
        RETURN NEW;
    END IF;

    IF CURRENT_DATE < NEW.start_date THEN
        NEW.status := 'Scheduled';
    ELSIF CURRENT_DATE > NEW.end_date THEN
        NEW.status := 'Completed';
    ELSE
        NEW.status := 'Ongoing';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_set_status_from_dates_trg ON events;

CREATE TRIGGER events_set_status_from_dates_trg
BEFORE INSERT OR UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION events_set_status_from_dates();

-- 7. Attendance Logs Table
CREATE TABLE IF NOT EXISTS attendance_logs (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL, -- Who scanned it
    attendance_date DATE NOT NULL,
    scan_time TIMESTAMP WITH TIME ZONE NOT NULL,
    action_session TEXT NOT NULL CHECK (action_session IN ('AM', 'PM')),
    scan_status TEXT NOT NULL DEFAULT 'Valid' CHECK (scan_status IN ('Valid', 'Duplicate', 'Invalid', 'Late')),
    scanner_device TEXT,
    remarks TEXT
);

-- Enable Realtime for specific tables (Required for Supabase Realtime client)
alter publication supabase_realtime add table events;
alter publication supabase_realtime add table event_participants;
alter publication supabase_realtime add table attendance_logs;
