
-- Enable necessary extensions (if needed, usually public is default)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Offices / Agencies Table
CREATE TABLE IF NOT EXISTS offices (
    office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Office certificate signatories.
-- Multiple active signatories can belong to one office; one can be marked as default.
CREATE TABLE IF NOT EXISTS tbl_signatory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL REFERENCES offices(office_id) ON DELETE CASCADE,
    label TEXT,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    esig_link TEXT,
    agency_name TEXT,
    agency_logo_url TEXT,
    header TEXT,
    sub_header TEXT,
    address TEXT,
    website TEXT,
    footer TEXT,
    post_nominals TEXT,
    certificate_template_variant TEXT DEFAULT 'with_serial' CHECK (certificate_template_variant IN ('with_serial', 'without_serial')),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE tbl_signatory
    ADD COLUMN IF NOT EXISTS label TEXT,
    ADD COLUMN IF NOT EXISTS agency_name TEXT,
    ADD COLUMN IF NOT EXISTS agency_logo_url TEXT,
    ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

DO $$
DECLARE
    constraint_name text;
BEGIN
    SELECT con.conname
    INTO constraint_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'tbl_signatory'
      AND nsp.nspname = 'public'
      AND con.contype = 'u'
      AND array_length(con.conkey, 1) = 1
      AND con.conkey[1] = (
          SELECT attnum
          FROM pg_attribute
          WHERE attrelid = rel.oid
            AND attname = 'office_id'
      )
    LIMIT 1;

    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE public.tbl_signatory DROP CONSTRAINT %I', constraint_name);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS tbl_signatory_one_default_per_office
    ON tbl_signatory(office_id)
    WHERE is_default = TRUE AND active = TRUE;

CREATE INDEX IF NOT EXISTS tbl_signatory_office_active_idx
    ON tbl_signatory(office_id, active, sort_order);

-- 2. Reference Locations Table (Provinces/Cities/Municipalities)
CREATE TABLE IF NOT EXISTS ref_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_huc TEXT NOT NULL,
    city_mun TEXT -- Nullable for Province level entries
);

-- 3. Users Table (Manual Auth, not Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL, -- Bcrypt hash
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Scanner', 'EventManager')),
    position TEXT,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    office_id BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. User Login Activity Table
CREATE TABLE IF NOT EXISTS user_login_activity (
    login_activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    auth_user_id UUID,
    username TEXT,
    login_method TEXT NOT NULL DEFAULT 'Password' CHECK (login_method IN ('Password', 'Google')),
    login_status TEXT NOT NULL DEFAULT 'Success' CHECK (login_status IN ('Success', 'Failed')),
    failure_reason TEXT,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS user_login_activity_user_id_created_at_idx
    ON user_login_activity(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS user_login_activity_created_at_idx
    ON user_login_activity(created_at DESC);

CREATE INDEX IF NOT EXISTS user_login_activity_auth_user_id_idx
    ON user_login_activity(auth_user_id);

-- 5. Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    venue TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL, -- Can be same as start_date
    event_serial TEXT,
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Ongoing', 'Completed', 'Cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    organize_by BIGINT REFERENCES offices(office_id) ON DELETE SET NULL,
    cop_primary_signatory_id BIGINT REFERENCES tbl_signatory(id) ON DELETE SET NULL,
    cop_secondary_signatory_id BIGINT REFERENCES tbl_signatory(id) ON DELETE SET NULL,
    has_accommodation BOOLEAN DEFAULT FALSE,
    registration_open BOOLEAN DEFAULT TRUE,
    auto_attendance_on_registration BOOLEAN NOT NULL DEFAULT FALSE,
    has_principal_delegates BOOLEAN NOT NULL DEFAULT FALSE,
    has_item_borrowing BOOLEAN NOT NULL DEFAULT FALSE,
    session TEXT NOT NULL DEFAULT 'All_Day' CHECK (session IN ('AM', 'PM', 'All_Day')),
    days_accommodation SMALLINT,
    dates_with_accom DATE[],
    food_inclusion TEXT[],
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    delete_reason TEXT
);

ALTER TABLE events
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS delete_reason TEXT,
    ADD COLUMN IF NOT EXISTS auto_attendance_on_registration BOOLEAN NOT NULL DEFAULT FALSE,
    -- Giveaways/freebies offered at registration (e.g. T-shirt sizes).
    ADD COLUMN IF NOT EXISTS giveaways JSONB,
    -- When FALSE, giveaway selection is closed for new registrants (sizes etc. become read-only).
    ADD COLUMN IF NOT EXISTS giveaways_open BOOLEAN DEFAULT TRUE,
    -- When TRUE, Delegates are further classified as Principal or Representative.
    ADD COLUMN IF NOT EXISTS has_principal_delegates BOOLEAN NOT NULL DEFAULT FALSE,
    -- Item borrowing is available only to events owned by the inventory-enabled offices.
    ADD COLUMN IF NOT EXISTS has_item_borrowing BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS cop_primary_signatory_id BIGINT REFERENCES tbl_signatory(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS cop_secondary_signatory_id BIGINT REFERENCES tbl_signatory(id) ON DELETE SET NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'events_cop_signatories_different'
          AND conrelid = 'public.events'::regclass
    ) THEN
        ALTER TABLE public.events
            ADD CONSTRAINT events_cop_signatories_different
            CHECK (
                cop_secondary_signatory_id IS NULL
                OR cop_primary_signatory_id IS DISTINCT FROM cop_secondary_signatory_id
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'events_item_borrowing_office_chk'
          AND conrelid = 'public.events'::regclass
    ) THEN
        ALTER TABLE public.events
            ADD CONSTRAINT events_item_borrowing_office_chk
            CHECK (NOT has_item_borrowing OR organize_by IN (3, 12));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS events_active_idx
    ON events(start_date DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS events_deleted_idx
    ON events(deleted_at DESC)
    WHERE deleted_at IS NOT NULL;

-- 6. Participants Table
CREATE TABLE IF NOT EXISTS participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_code TEXT NOT NULL UNIQUE, -- Used for QR
    full_name TEXT NOT NULL,
    email TEXT,
    mobile_no TEXT,
    gender TEXT,
    position TEXT,
    prc_license_no TEXT CHECK (prc_license_no IS NULL OR prc_license_no ~ '^[0-9]{1,20}$'),
    office TEXT, -- Text representation of office/LGU if not linked strictly
    location_id BIGINT REFERENCES ref_locations(location_id) ON DELETE SET NULL,
    age_group TEXT,
    pwd TEXT DEFAULT 'No',
    indigenous_people TEXT DEFAULT 'No',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Event Participants Junction Table (Registration)
CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    registration_status TEXT NOT NULL DEFAULT 'Registered' CHECK (registration_status IN ('Registered', 'Cancelled')),
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    accommodation_pax INT DEFAULT 0 CHECK (accommodation_pax >= 0),
    role TEXT NOT NULL DEFAULT 'Delegate' CHECK (role IN ('Delegate', 'Speaker', 'Secretariat', 'Guest', 'VIP')),
    -- Only set for events with has_principal_delegates, and only on Delegate rows.
    delegate_type TEXT,
    needs_accommodation BOOLEAN DEFAULT FALSE,
    accept_photo_video BOOLEAN NOT NULL DEFAULT FALSE,
    store_to_db BOOLEAN NOT NULL DEFAULT FALSE,
    date_accommodation DATE[],
    ca_serial_no INT NULL,
    ca_issued_at TIMESTAMP WITH TIME ZONE NULL,
    ca_email_sent_at TIMESTAMP WITH TIME ZONE NULL,
    cop_email_sent_at TIMESTAMP WITH TIME ZONE NULL,
    qr_email_sent_at TIMESTAMP WITH TIME ZONE NULL,
    UNIQUE(event_id, participant_id)
);

ALTER TABLE event_participants
    ADD COLUMN IF NOT EXISTS delegate_type TEXT;

-- Couples delegate_type to role so the two can never disagree.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'event_participants_delegate_type_chk'
          AND conrelid = 'public.event_participants'::regclass
    ) THEN
        ALTER TABLE public.event_participants
            ADD CONSTRAINT event_participants_delegate_type_chk
            CHECK (
                delegate_type IS NULL
                OR (delegate_type IN ('Principal', 'Representative') AND role = 'Delegate')
            );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS event_participants_principal_idx
    ON event_participants(event_id)
    WHERE delegate_type = 'Principal';

-- Ensure CA serial numbers are unique per event (skips NULL rows that haven't been issued yet).
CREATE UNIQUE INDEX IF NOT EXISTS event_participants_ca_serial_unique
    ON event_participants(event_id, ca_serial_no)
    WHERE ca_serial_no IS NOT NULL;

-- Assigns the next sequential CA serial numbers to the given participants for an event.
-- Skips participants that already have a serial. Refuses to assign when the event has no event_serial.
-- Uses a transaction-level advisory lock keyed by event_id to make concurrent calls safe.
CREATE OR REPLACE FUNCTION assign_ca_serials(
    p_event_id BIGINT,
    p_participant_ids BIGINT[]
)
RETURNS TABLE(out_participant_id BIGINT, out_ca_serial_no INT) AS $$
DECLARE
    v_event_serial TEXT;
    v_next_no INT;
    v_participant_id BIGINT;
BEGIN
    SELECT event_serial INTO v_event_serial FROM events WHERE event_id = p_event_id;

    IF v_event_serial IS NULL OR btrim(v_event_serial) = '' THEN
        RAISE EXCEPTION 'Event % does not use reference coding', p_event_id
            USING ERRCODE = 'check_violation';
    END IF;

    PERFORM pg_advisory_xact_lock(p_event_id);

    SELECT COALESCE(MAX(ep.ca_serial_no), 0) INTO v_next_no
    FROM event_participants ep
    WHERE ep.event_id = p_event_id;

    FOREACH v_participant_id IN ARRAY p_participant_ids LOOP
        UPDATE event_participants ep
        SET ca_serial_no = v_next_no + 1,
            ca_issued_at = NOW()
        WHERE ep.event_id = p_event_id
          AND ep.participant_id = v_participant_id
          AND ep.ca_serial_no IS NULL;

        IF FOUND THEN
            v_next_no := v_next_no + 1;
        END IF;
    END LOOP;

    RETURN QUERY
    SELECT ep.participant_id::BIGINT, ep.ca_serial_no::INT
    FROM event_participants ep
    WHERE ep.event_id = p_event_id
      AND ep.participant_id = ANY(p_participant_ids);
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION events_set_status_from_dates()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.status = 'Cancelled' THEN
        RETURN NEW;
    END IF;

    IF CURRENT_DATE < NEW.start_date THEN
        NEW.status := 'Scheduled';
    ELSIF CURRENT_DATE > NEW.end_date THEN
        NEW.status := 'Completed';
    ELSE
        NEW.status := 'Ongoing';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_set_status_from_dates_trg ON events;

CREATE TRIGGER events_set_status_from_dates_trg
BEFORE INSERT OR UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION events_set_status_from_dates();

-- 8. Attendance Logs Table
CREATE TABLE IF NOT EXISTS attendance_logs (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT REFERENCES participants(participant_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL, -- Who scanned it
    attendance_date DATE NOT NULL,
    scan_time TIMESTAMP WITH TIME ZONE NOT NULL,
    action_session TEXT NOT NULL CHECK (action_session IN ('AM', 'PM')),
    scan_status TEXT NOT NULL DEFAULT 'Valid' CHECK (scan_status IN ('Valid', 'Duplicate', 'Invalid', 'Late')),
    scanner_device TEXT,
    remarks TEXT
);

-- Remove the earlier global trigger implementation, if present. Staff-side Add
-- Participant attendance remains controlled by its own explicit checkbox.
DROP TRIGGER IF EXISTS event_participants_auto_attendance_trg
ON public.event_participants;

DROP FUNCTION IF EXISTS public.log_attendance_on_event_registration();

-- Called only by the public Event Registration page after a successful
-- registration. The function validates the event setting, a recent matching
-- registration, and the Philippine event date before writing attendance.
CREATE OR REPLACE FUNCTION public.log_public_event_registration_attendance(
    p_event_id BIGINT,
    p_participant_code TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_event public.events%ROWTYPE;
    v_participant_id BIGINT;
    v_scan_time TIMESTAMP WITH TIME ZONE := clock_timestamp();
    v_attendance_date DATE;
    v_action_session TEXT;
BEGIN
    IF p_event_id IS NULL
       OR p_event_id <= 0
       OR NULLIF(BTRIM(p_participant_code), '') IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT p.participant_id
    INTO v_participant_id
    FROM public.participants p
    INNER JOIN public.event_participants ep
        ON ep.participant_id = p.participant_id
       AND ep.event_id = p_event_id
       AND ep.registration_status = 'Registered'
       AND ep.registered_at >= v_scan_time - INTERVAL '5 minutes'
    WHERE p.participant_code = p_participant_code
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT *
    INTO v_event
    FROM public.events
    WHERE event_id = p_event_id
      AND deleted_at IS NULL;

    IF NOT FOUND OR NOT COALESCE(v_event.auto_attendance_on_registration, FALSE) THEN
        RETURN NULL;
    END IF;

    v_attendance_date := (v_scan_time AT TIME ZONE 'Asia/Manila')::DATE;

    IF v_attendance_date < v_event.start_date
       OR v_attendance_date > v_event.end_date THEN
        RETURN NULL;
    END IF;

    v_action_session := CASE
        WHEN v_event.session = 'PM' THEN 'PM'
        ELSE 'AM'
    END;

    INSERT INTO public.attendance_logs (
        event_id,
        participant_id,
        user_id,
        attendance_date,
        scan_time,
        action_session,
        scan_status,
        scanner_device,
        remarks
    )
    SELECT
        p_event_id,
        v_participant_id,
        NULL,
        v_attendance_date,
        v_scan_time,
        v_action_session,
        'Valid',
        'Event Registration',
        'Auto-logged from Event Registration (' || v_action_session || ')'
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.attendance_logs
        WHERE event_id = p_event_id
          AND participant_id = v_participant_id
          AND attendance_date = v_attendance_date
          AND action_session = v_action_session
          AND scan_status IN ('Valid', 'Late')
    );

    RETURN v_action_session;
END;
$$;

REVOKE ALL ON FUNCTION public.log_public_event_registration_attendance(BIGINT, TEXT)
FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.log_public_event_registration_attendance(BIGINT, TEXT)
TO anon, authenticated;

-- 9. Giveaway / Freebie Claim Logs Table
CREATE TABLE IF NOT EXISTS giveaway_claim_logs (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    claimed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    claim_status TEXT NOT NULL DEFAULT 'Claimed',
    giveaway_snapshot JSONB,
    scanner_device TEXT,
    remarks TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS giveaway_claim_once_per_event
ON giveaway_claim_logs(event_id, participant_id);

-- 9b. Principal Delegate Arrival Logs
-- Kept apart from attendance_logs: a promotion at the scanner or a walk-in
-- registration is an arrival whose time differs from the attendance record.
CREATE TABLE IF NOT EXISTS principal_arrival_logs (
    arrival_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    arrived_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    arrival_date DATE NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Manila')::DATE),
    source TEXT NOT NULL DEFAULT 'Scan'
        CHECK (source IN ('Scan', 'Promoted', 'AutoRegistered')),
    scanner_device TEXT,
    remarks TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS principal_arrival_once_per_day
ON principal_arrival_logs(event_id, participant_id, arrival_date);

CREATE INDEX IF NOT EXISTS principal_arrival_logs_event_idx
ON principal_arrival_logs(event_id, arrived_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'principal_arrival_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.principal_arrival_logs;
    END IF;
END $$;

-- 9c. Pre-test / Post-test
--
-- An event may run a Pre-test (before the session) and a Post-test (after), each a
-- set of multiple-choice questions reached by its own public QR code. A test exists
-- only if a row is present in event_tests, so no boolean flag can disagree with the
-- data. A Certificate of Completion requires that both enabled tests were SUBMITTED,
-- not passed -- `passing_score` is reporting-only. See lib/eventTests.ts.
CREATE TABLE IF NOT EXISTS event_tests (
    test_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    test_type     TEXT   NOT NULL CHECK (test_type IN ('Pre', 'Post')),
    title         TEXT   NOT NULL,
    instructions  TEXT,
    passing_score NUMERIC(5,2),
    is_open       BOOLEAN NOT NULL DEFAULT TRUE,
    show_score    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(event_id, test_type)
);

CREATE TABLE IF NOT EXISTS event_test_questions (
    question_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id       BIGINT NOT NULL REFERENCES event_tests(test_id) ON DELETE CASCADE,
    position      INT    NOT NULL,
    question_text TEXT   NOT NULL,
    -- [{ "key": "a", "label": "…" }, …] -- `key` is what a submission stores, so
    -- reordering or relabelling a choice never rewrites past answers.
    choices       JSONB  NOT NULL,
    correct_key   TEXT   NOT NULL,
    points        NUMERIC(5,2) NOT NULL DEFAULT 1,
    UNIQUE(test_id, position)
);

CREATE TABLE IF NOT EXISTS event_test_submissions (
    submission_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id          BIGINT NOT NULL REFERENCES event_tests(test_id) ON DELETE CASCADE,
    event_id         BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id   BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    -- Snapshot, so the results report stays readable if the participant row changes.
    participant_name TEXT   NOT NULL,
    submitted_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    score            NUMERIC(6,2) NOT NULL,
    max_score        NUMERIC(6,2) NOT NULL,
    -- { "<question_id>": "b", … } -- kept for per-question item analysis.
    answers          JSONB  NOT NULL,
    UNIQUE(test_id, participant_id)
);

CREATE INDEX IF NOT EXISTS event_test_submissions_event_idx
    ON event_test_submissions(event_id, test_id);

CREATE INDEX IF NOT EXISTS event_test_questions_test_idx
    ON event_test_questions(test_id, position);

-- The test page is unauthenticated and runs on the anon key, so it must never query
-- event_test_questions directly -- that table carries `correct_key`. These two
-- functions hand out only what the page needs: get_event_test omits the answer key,
-- and submit_event_test scores server-side.
CREATE OR REPLACE FUNCTION public.get_event_test(
    p_event_id BIGINT,
    p_test_type TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_event     public.events%ROWTYPE;
    v_test      public.event_tests%ROWTYPE;
    v_questions JSONB;
BEGIN
    IF p_event_id IS NULL OR p_test_type NOT IN ('Pre', 'Post') THEN
        RETURN NULL;
    END IF;

    SELECT * INTO v_event
    FROM public.events
    WHERE event_id = p_event_id
      AND deleted_at IS NULL;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT * INTO v_test
    FROM public.event_tests
    WHERE event_id = p_event_id
      AND test_type = p_test_type;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY q.position), '[]'::jsonb)
    INTO v_questions
    FROM (
        SELECT question_id, position, question_text, choices, points
        FROM public.event_test_questions
        WHERE test_id = v_test.test_id
    ) q;

    RETURN jsonb_build_object(
        'event_id',     v_event.event_id,
        'event_name',   v_event.event_name,
        'venue',        v_event.venue,
        'start_date',   v_event.start_date,
        'end_date',     v_event.end_date,
        'test_id',      v_test.test_id,
        'test_type',    v_test.test_type,
        'title',        v_test.title,
        'instructions', v_test.instructions,
        'is_open',      v_test.is_open,
        'show_score',   v_test.show_score,
        'questions',    v_questions
    );
END;
$$;

REVOKE ALL ON FUNCTION public.get_event_test(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_event_test(BIGINT, TEXT) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.submit_event_test(
    p_event_id BIGINT,
    p_test_type TEXT,
    p_participant_id BIGINT,
    p_answers JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_test     public.event_tests%ROWTYPE;
    v_name     TEXT;
    v_answers  JSONB := COALESCE(p_answers, '{}'::jsonb);
    v_score    NUMERIC(6,2) := 0;
    v_max      NUMERIC(6,2) := 0;
    v_existing public.event_test_submissions%ROWTYPE;
    v_inserted public.event_test_submissions%ROWTYPE;
BEGIN
    IF p_event_id IS NULL
       OR p_participant_id IS NULL
       OR p_test_type NOT IN ('Pre', 'Post') THEN
        RAISE EXCEPTION 'Invalid test submission.' USING ERRCODE = 'check_violation';
    END IF;

    SELECT t.* INTO v_test
    FROM public.event_tests t
    INNER JOIN public.events e
        ON e.event_id = t.event_id
       AND e.deleted_at IS NULL
    WHERE t.event_id = p_event_id
      AND t.test_type = p_test_type;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'This test is not available.' USING ERRCODE = 'no_data_found';
    END IF;

    -- The page only ever offers names from this event's roster; this is what keeps
    -- that true server-side, where it cannot be bypassed.
    SELECT p.full_name INTO v_name
    FROM public.participants p
    INNER JOIN public.event_participants ep
        ON ep.participant_id = p.participant_id
       AND ep.event_id = p_event_id
       AND ep.registration_status = 'Registered'
    WHERE p.participant_id = p_participant_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'That name is not registered for this event.' USING ERRCODE = 'no_data_found';
    END IF;

    -- An existing submission wins: the test is taken once, and a second scan must
    -- not overwrite the first set of answers.
    SELECT * INTO v_existing
    FROM public.event_test_submissions
    WHERE test_id = v_test.test_id
      AND participant_id = p_participant_id;

    IF FOUND THEN
        RETURN jsonb_build_object(
            'already_submitted', TRUE,
            'score',             v_existing.score,
            'max_score',         v_existing.max_score,
            'submitted_at',      v_existing.submitted_at
        );
    END IF;

    IF NOT COALESCE(v_test.is_open, FALSE) THEN
        RAISE EXCEPTION 'This test is closed.' USING ERRCODE = 'check_violation';
    END IF;

    SELECT
        COALESCE(SUM(q.points), 0),
        COALESCE(SUM(CASE WHEN v_answers ->> q.question_id::TEXT = q.correct_key
                          THEN q.points ELSE 0 END), 0)
    INTO v_max, v_score
    FROM public.event_test_questions q
    WHERE q.test_id = v_test.test_id;

    INSERT INTO public.event_test_submissions (
        test_id, event_id, participant_id, participant_name, score, max_score, answers
    )
    VALUES (
        v_test.test_id, p_event_id, p_participant_id, v_name, v_score, v_max, v_answers
    )
    ON CONFLICT (test_id, participant_id) DO NOTHING
    RETURNING * INTO v_inserted;

    -- Lost a race against a concurrent submit: report the row that won, so the score
    -- shown always matches the score stored.
    IF v_inserted.submission_id IS NULL THEN
        SELECT * INTO v_existing
        FROM public.event_test_submissions
        WHERE test_id = v_test.test_id
          AND participant_id = p_participant_id;

        RETURN jsonb_build_object(
            'already_submitted', TRUE,
            'score',             v_existing.score,
            'max_score',         v_existing.max_score,
            'submitted_at',      v_existing.submitted_at
        );
    END IF;

    RETURN jsonb_build_object(
        'already_submitted', FALSE,
        'score',             v_inserted.score,
        'max_score',         v_inserted.max_score,
        'submitted_at',      v_inserted.submitted_at
    );
END;
$$;

REVOKE ALL ON FUNCTION public.submit_event_test(BIGINT, TEXT, BIGINT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_event_test(BIGINT, TEXT, BIGINT, JSONB) TO anon, authenticated;

-- Enable Realtime for specific tables (Required for Supabase Realtime client)
alter publication supabase_realtime add table events;
alter publication supabase_realtime add table event_participants;
alter publication supabase_realtime add table attendance_logs;

-- 10. Feature Announcements Table
CREATE TABLE IF NOT EXISTS feature_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'warning', 'success')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Track which users have seen/dismissed announcements
CREATE TABLE IF NOT EXISTS announcement_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL REFERENCES feature_announcements(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(announcement_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_active ON feature_announcements(is_active);
CREATE INDEX IF NOT EXISTS idx_announcement_views_user ON announcement_views(user_id);

-- 11. Audit Logs Table
--
-- Record-level audit trail for changes made through the app. Written by the app,
-- not by triggers: auth is custom (public.users + bcrypt on the client) so the
-- database cannot know which user performed an action — every write passes the
-- actor explicitly. See lib/auditLog.ts.
--
-- actor_name / actor_role / entity_label / event_name are denormalized snapshots
-- so the trail stays readable after the referenced rows are deleted.
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- WHO
    actor_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    actor_name    TEXT,
    actor_role    TEXT,

    -- WHAT
    action        TEXT NOT NULL CHECK (action IN ('Create', 'Update', 'Delete', 'PermanentDelete', 'Restore')),
    entity_type   TEXT NOT NULL CHECK (entity_type IN ('Event', 'EventParticipant', 'Participant', 'User')),
    entity_id     BIGINT,
    entity_label  TEXT,

    -- WHERE: lets the trail be scoped to a single event. NULL for User rows.
    event_id      BIGINT REFERENCES events(event_id) ON DELETE SET NULL,
    event_name    TEXT,

    -- DETAIL
    -- changes: { "venue": { "from": "Hall A", "to": "Hall B" } } — only fields
    -- that actually changed. snapshot: the full row, kept for deletes.
    changes       JSONB,
    snapshot      JSONB,
    reason        TEXT,
    user_agent    TEXT,

    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx
    ON audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_entity_idx
    ON audit_logs(entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_event_idx
    ON audit_logs(event_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_actor_idx
    ON audit_logs(actor_user_id, created_at DESC);

-- Append-only: the app inserts and reads, and can never rewrite history.
REVOKE UPDATE, DELETE ON audit_logs FROM anon, authenticated;

-- 12. Borrowable Items & Borrowed Items (Item Lending Feature)
--
-- Master inventory of items available for borrowing during events (tablets, equipment, etc.)
-- Items are scoped per office to prevent cross-office borrowing
CREATE TABLE IF NOT EXISTS borrowable_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL REFERENCES offices(office_id) ON DELETE CASCADE,
    item_code TEXT NOT NULL,  -- QR code content, uniquely identifies the physical item
    item_name TEXT NOT NULL,          -- e.g., "Tablet A", "Device 01"
    item_description TEXT,            -- e.g., model, serial number, specs
    item_category TEXT,               -- e.g., "Tablet", "Laptop", "Equipment"
    status TEXT NOT NULL DEFAULT 'Available' CHECK (status IN ('Available', 'Damaged', 'Archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(office_id, item_code)  -- Unique item code per office
);

CREATE INDEX IF NOT EXISTS borrowable_items_office_idx
    ON borrowable_items(office_id);

CREATE INDEX IF NOT EXISTS borrowable_items_office_status_idx
    ON borrowable_items(office_id, status);

CREATE INDEX IF NOT EXISTS borrowable_items_item_code_idx
    ON borrowable_items(item_code);

-- Transaction log tracking all borrow/return events
CREATE TABLE IF NOT EXISTS borrowed_items (
    borrow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES borrowable_items(item_id) ON DELETE RESTRICT,
    borrowed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    returned_at TIMESTAMP WITH TIME ZONE,  -- NULL = item still borrowed
    returned_by_participant_id BIGINT REFERENCES participants(participant_id) ON DELETE SET NULL,
    scanner_device TEXT,  -- Device label that recorded the transaction
    notes TEXT,           -- Optional condition notes, damage report, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for finding active (unreturned) borrows for a participant
CREATE INDEX IF NOT EXISTS borrowed_items_active_idx
    ON borrowed_items(participant_id, returned_at)
    WHERE returned_at IS NULL;

-- Index for event history queries
CREATE INDEX IF NOT EXISTS borrowed_items_event_idx
    ON borrowed_items(event_id, borrowed_at DESC);

-- Index for item history
CREATE INDEX IF NOT EXISTS borrowed_items_item_idx
    ON borrowed_items(item_id, borrowed_at DESC);

-- Prevent duplicate active borrow for same item (item can only be borrowed once at a time)
CREATE UNIQUE INDEX IF NOT EXISTS borrowed_items_active_item_unique
    ON borrowed_items(item_id)
    WHERE returned_at IS NULL;

-- Function: Create a borrow record (participant borrows an item)
CREATE OR REPLACE FUNCTION create_borrow(
    p_event_id BIGINT,
    p_participant_id BIGINT,
    p_item_id BIGINT,
    p_scanner_device TEXT DEFAULT NULL
) RETURNS borrowed_items AS $$
DECLARE
    v_borrow borrowed_items;
    v_existing_borrow borrowed_items%ROWTYPE;
BEGIN
    -- Check if item is already borrowed and not returned
    SELECT * INTO v_existing_borrow
    FROM borrowed_items
    WHERE item_id = p_item_id AND returned_at IS NULL
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'Item % is already borrowed', p_item_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    INSERT INTO borrowed_items (event_id, participant_id, item_id, scanner_device)
    VALUES (p_event_id, p_participant_id, p_item_id, p_scanner_device)
    RETURNING * INTO v_borrow;

    RETURN v_borrow;
END;
$$ LANGUAGE plpgsql;

-- Function: Return a borrowed item
CREATE OR REPLACE FUNCTION return_borrow(
    p_borrow_id BIGINT,
    p_returned_by_participant_id BIGINT,
    p_scanner_device TEXT DEFAULT NULL,
    p_notes TEXT DEFAULT NULL
) RETURNS borrowed_items AS $$
DECLARE
    v_borrow borrowed_items;
BEGIN
    UPDATE borrowed_items
    SET returned_at = NOW(),
        returned_by_participant_id = p_returned_by_participant_id,
        scanner_device = COALESCE(p_scanner_device, scanner_device),
        notes = COALESCE(p_notes, notes)
    WHERE borrow_id = p_borrow_id AND returned_at IS NULL
    RETURNING * INTO v_borrow;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Borrow record % not found or already returned', p_borrow_id
            USING ERRCODE = 'no_data_found';
    END IF;

    RETURN v_borrow;
END;
$$ LANGUAGE plpgsql;

-- Function: Get active (unreturned) borrows for a participant in an event
CREATE OR REPLACE FUNCTION get_active_borrows(
    p_participant_id BIGINT,
    p_event_id BIGINT
) RETURNS TABLE(
    borrow_id BIGINT,
    item_id BIGINT,
    item_name TEXT,
    item_code TEXT,
    borrowed_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    -- Every text column is cast explicitly: RETURN QUERY demands an exact type
    -- match against the declared OUT columns and will not coerce a varchar(n)
    -- to text on its own.
    RETURN QUERY
    SELECT
        bi.borrow_id,
        bi.item_id,
        bItems.item_name::TEXT,
        bItems.item_code::TEXT,
        bi.borrowed_at
    FROM borrowed_items bi
    JOIN borrowable_items bItems ON bi.item_id = bItems.item_id
    WHERE bi.participant_id = p_participant_id
        AND bi.event_id = p_event_id
        AND bi.returned_at IS NULL
    ORDER BY bi.borrowed_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Function: Get borrow history for an event
CREATE OR REPLACE FUNCTION get_borrow_history(
    p_event_id BIGINT
) RETURNS TABLE(
    borrow_id BIGINT,
    participant_id BIGINT,
    participant_name TEXT,
    item_id BIGINT,
    item_name TEXT,
    borrowed_at TIMESTAMP WITH TIME ZONE,
    returned_at TIMESTAMP WITH TIME ZONE,
    duration_minutes INT,
    status TEXT
) AS $$
BEGIN
    -- participants.full_name is varchar(150) in deployed databases, so the cast
    -- is required, not cosmetic: without it RETURN QUERY raises 42804 and the
    -- whole report comes back as an error.
    RETURN QUERY
    SELECT
        bi.borrow_id,
        bi.participant_id,
        p.full_name::TEXT,
        bi.item_id,
        bItems.item_name::TEXT,
        bi.borrowed_at,
        bi.returned_at,
        EXTRACT(EPOCH FROM (COALESCE(bi.returned_at, NOW()) - bi.borrowed_at))::INT / 60,
        (CASE WHEN bi.returned_at IS NULL THEN 'Unreturned' ELSE 'Returned' END)::TEXT
    FROM borrowed_items bi
    JOIN participants p ON bi.participant_id = p.participant_id
    JOIN borrowable_items bItems ON bi.item_id = bItems.item_id
    WHERE bi.event_id = p_event_id
    ORDER BY bi.borrowed_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Function: Get borrow history for a participant
CREATE OR REPLACE FUNCTION get_participant_borrow_history(
    p_participant_id BIGINT,
    p_event_id BIGINT
) RETURNS TABLE(
    borrow_id BIGINT,
    item_id BIGINT,
    item_name TEXT,
    item_code TEXT,
    borrowed_at TIMESTAMP WITH TIME ZONE,
    returned_at TIMESTAMP WITH TIME ZONE,
    duration_minutes INT,
    status TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        bi.borrow_id,
        bi.item_id,
        bItems.item_name::TEXT,
        bItems.item_code::TEXT,
        bi.borrowed_at,
        bi.returned_at,
        EXTRACT(EPOCH FROM (COALESCE(bi.returned_at, NOW()) - bi.borrowed_at))::INT / 60,
        (CASE WHEN bi.returned_at IS NULL THEN 'Unreturned' ELSE 'Returned' END)::TEXT
    FROM borrowed_items bi
    JOIN borrowable_items bItems ON bi.item_id = bItems.item_id
    WHERE bi.participant_id = p_participant_id
        AND bi.event_id = p_event_id
    ORDER BY bi.borrowed_at DESC;
END;
$$ LANGUAGE plpgsql;
