-- Audit trail for record-level changes made through the app.
--
-- Written by the app, not by triggers: auth is custom (public.users + bcrypt on
-- the client) so the database has no way to know which user performed an action.
-- Every write therefore passes the actor explicitly. See lib/auditLog.ts.
--
-- actor_name / actor_role / entity_label / event_name are denormalized snapshots
-- so the trail stays readable after the referenced rows are deleted.
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- WHO
    actor_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    actor_name    TEXT,
    actor_role    TEXT,

    -- WHAT
    action        TEXT NOT NULL CHECK (action IN ('Create', 'Update', 'Delete', 'PermanentDelete', 'Restore')),
    entity_type   TEXT NOT NULL CHECK (entity_type IN ('Event', 'EventParticipant', 'Participant', 'User')),
    entity_id     BIGINT,
    entity_label  TEXT,

    -- WHERE: lets the trail be scoped to a single event. NULL for User rows.
    event_id      BIGINT REFERENCES events(event_id) ON DELETE SET NULL,
    event_name    TEXT,

    -- DETAIL
    -- changes: { "venue": { "from": "Hall A", "to": "Hall B" } } — only fields
    -- that actually changed. snapshot: the full row, kept for deletes.
    changes       JSONB,
    snapshot      JSONB,
    reason        TEXT,
    user_agent    TEXT,

    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx
    ON audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_entity_idx
    ON audit_logs(entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_event_idx
    ON audit_logs(event_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_actor_idx
    ON audit_logs(actor_user_id, created_at DESC);

-- Append-only: the app inserts and reads, and can never rewrite history.
REVOKE UPDATE, DELETE ON audit_logs FROM anon, authenticated;
