-- Pre-test / Post-test.
--
-- An event may run a Pre-test (before the session) and a Post-test (after), each
-- a set of multiple-choice questions with its own public QR code. A participant
-- takes a test by picking their name from this event's roster -- no login -- and
-- answering every question once.
--
-- Both tests are optional per event: a test exists only if a row is present in
-- event_tests, so there is no boolean flag that can disagree with the data.
--
-- Eligibility note: a Certificate of Completion requires that both enabled tests
-- were SUBMITTED, not passed. `passing_score` below is reporting-only -- see
-- lib/eventTests.ts.

CREATE TABLE IF NOT EXISTS public.event_tests (
    test_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    test_type     TEXT   NOT NULL CHECK (test_type IN ('Pre', 'Post')),
    title         TEXT   NOT NULL,
    instructions  TEXT,
    -- Percent benchmark shown in the results report. Never gates a certificate.
    passing_score NUMERIC(5,2),
    -- Mirrors events.registration_open: closed means the QR still resolves but
    -- no new submissions are accepted.
    is_open       BOOLEAN NOT NULL DEFAULT TRUE,
    -- Whether the participant sees their score on the thank-you screen.
    show_score    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(event_id, test_type)
);

CREATE TABLE IF NOT EXISTS public.event_test_questions (
    question_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id       BIGINT NOT NULL REFERENCES public.event_tests(test_id) ON DELETE CASCADE,
    position      INT    NOT NULL,
    question_text TEXT   NOT NULL,
    -- [{ "key": "a", "label": "…" }, …] -- `key` is what a submission stores, so
    -- reordering or relabelling a choice never rewrites past answers.
    choices       JSONB  NOT NULL,
    correct_key   TEXT   NOT NULL,
    points        NUMERIC(5,2) NOT NULL DEFAULT 1,
    UNIQUE(test_id, position)
);

CREATE TABLE IF NOT EXISTS public.event_test_submissions (
    submission_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id          BIGINT NOT NULL REFERENCES public.event_tests(test_id) ON DELETE CASCADE,
    event_id         BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    participant_id   BIGINT NOT NULL REFERENCES public.participants(participant_id) ON DELETE CASCADE,
    -- Snapshot, so the results report stays readable if the participant row changes.
    participant_name TEXT   NOT NULL,
    submitted_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    score            NUMERIC(6,2) NOT NULL,
    max_score        NUMERIC(6,2) NOT NULL,
    -- { "<question_id>": "b", … } -- kept for per-question item analysis.
    answers          JSONB  NOT NULL,
    -- One attempt per participant per test.
    UNIQUE(test_id, participant_id)
);

CREATE INDEX IF NOT EXISTS event_test_submissions_event_idx
    ON public.event_test_submissions(event_id, test_id);

CREATE INDEX IF NOT EXISTS event_test_questions_test_idx
    ON public.event_test_questions(test_id, position);

-- ─────────────────────────────────────────────────────────────────────────────
-- Public entry points
--
-- The test page is unauthenticated and runs on the anon key, so it must never
-- query event_test_questions directly -- that table carries `correct_key`. Both
-- functions below are SECURITY DEFINER and hand out only what the page needs:
-- get_event_test omits the answer key, and scoring happens server-side.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.get_event_test(
    p_event_id BIGINT,
    p_test_type TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_event     public.events%ROWTYPE;
    v_test      public.event_tests%ROWTYPE;
    v_questions JSONB;
BEGIN
    IF p_event_id IS NULL OR p_test_type NOT IN ('Pre', 'Post') THEN
        RETURN NULL;
    END IF;

    SELECT * INTO v_event
    FROM public.events
    WHERE event_id = p_event_id
      AND deleted_at IS NULL;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT * INTO v_test
    FROM public.event_tests
    WHERE event_id = p_event_id
      AND test_type = p_test_type;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY q.position), '[]'::jsonb)
    INTO v_questions
    FROM (
        SELECT question_id, position, question_text, choices, points
        FROM public.event_test_questions
        WHERE test_id = v_test.test_id
    ) q;

    RETURN jsonb_build_object(
        'event_id',     v_event.event_id,
        'event_name',   v_event.event_name,
        'venue',        v_event.venue,
        'start_date',   v_event.start_date,
        'end_date',     v_event.end_date,
        'test_id',      v_test.test_id,
        'test_type',    v_test.test_type,
        'title',        v_test.title,
        'instructions', v_test.instructions,
        'is_open',      v_test.is_open,
        'show_score',   v_test.show_score,
        'questions',    v_questions
    );
END;
$$;

REVOKE ALL ON FUNCTION public.get_event_test(BIGINT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_event_test(BIGINT, TEXT) TO anon, authenticated;


CREATE OR REPLACE FUNCTION public.submit_event_test(
    p_event_id BIGINT,
    p_test_type TEXT,
    p_participant_id BIGINT,
    p_answers JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_test     public.event_tests%ROWTYPE;
    v_name     TEXT;
    v_answers  JSONB := COALESCE(p_answers, '{}'::jsonb);
    v_score    NUMERIC(6,2) := 0;
    v_max      NUMERIC(6,2) := 0;
    v_existing public.event_test_submissions%ROWTYPE;
    v_inserted public.event_test_submissions%ROWTYPE;
BEGIN
    IF p_event_id IS NULL
       OR p_participant_id IS NULL
       OR p_test_type NOT IN ('Pre', 'Post') THEN
        RAISE EXCEPTION 'Invalid test submission.' USING ERRCODE = 'check_violation';
    END IF;

    SELECT t.* INTO v_test
    FROM public.event_tests t
    INNER JOIN public.events e
        ON e.event_id = t.event_id
       AND e.deleted_at IS NULL
    WHERE t.event_id = p_event_id
      AND t.test_type = p_test_type;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'This test is not available.' USING ERRCODE = 'no_data_found';
    END IF;

    -- The page only ever offers names from this event's roster; this is what keeps
    -- that true server-side, where it cannot be bypassed.
    SELECT p.full_name INTO v_name
    FROM public.participants p
    INNER JOIN public.event_participants ep
        ON ep.participant_id = p.participant_id
       AND ep.event_id = p_event_id
       AND ep.registration_status = 'Registered'
    WHERE p.participant_id = p_participant_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'That name is not registered for this event.' USING ERRCODE = 'no_data_found';
    END IF;

    -- An existing submission wins: the test is taken once, and a second scan must
    -- not overwrite the first set of answers.
    SELECT * INTO v_existing
    FROM public.event_test_submissions
    WHERE test_id = v_test.test_id
      AND participant_id = p_participant_id;

    IF FOUND THEN
        RETURN jsonb_build_object(
            'already_submitted', TRUE,
            'score',             v_existing.score,
            'max_score',         v_existing.max_score,
            'submitted_at',      v_existing.submitted_at
        );
    END IF;

    IF NOT COALESCE(v_test.is_open, FALSE) THEN
        RAISE EXCEPTION 'This test is closed.' USING ERRCODE = 'check_violation';
    END IF;

    SELECT
        COALESCE(SUM(q.points), 0),
        COALESCE(SUM(CASE WHEN v_answers ->> q.question_id::TEXT = q.correct_key
                          THEN q.points ELSE 0 END), 0)
    INTO v_max, v_score
    FROM public.event_test_questions q
    WHERE q.test_id = v_test.test_id;

    INSERT INTO public.event_test_submissions (
        test_id, event_id, participant_id, participant_name, score, max_score, answers
    )
    VALUES (
        v_test.test_id, p_event_id, p_participant_id, v_name, v_score, v_max, v_answers
    )
    ON CONFLICT (test_id, participant_id) DO NOTHING
    RETURNING * INTO v_inserted;

    -- Lost a race against a concurrent submit: report the row that won, so the
    -- score shown always matches the score stored.
    IF v_inserted.submission_id IS NULL THEN
        SELECT * INTO v_existing
        FROM public.event_test_submissions
        WHERE test_id = v_test.test_id
          AND participant_id = p_participant_id;

        RETURN jsonb_build_object(
            'already_submitted', TRUE,
            'score',             v_existing.score,
            'max_score',         v_existing.max_score,
            'submitted_at',      v_existing.submitted_at
        );
    END IF;

    RETURN jsonb_build_object(
        'already_submitted', FALSE,
        'score',             v_inserted.score,
        'max_score',         v_inserted.max_score,
        'submitted_at',      v_inserted.submitted_at
    );
END;
$$;

REVOKE ALL ON FUNCTION public.submit_event_test(BIGINT, TEXT, BIGINT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_event_test(BIGINT, TEXT, BIGINT, JSONB) TO anon, authenticated;
