-- Arrival log for Principal delegates.
--
-- Separate from attendance_logs because an arrival is not always the attendance
-- scan: a Representative promoted to Principal at the scanner arrives after
-- their attendance was already recorded, and a walk-in registers and arrives in
-- one step. This table is the record of what was announced, and when.

CREATE TABLE IF NOT EXISTS public.principal_arrival_logs (
    arrival_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES public.participants(participant_id) ON DELETE CASCADE,
    -- NULL when the announcing user is later deleted.
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    arrived_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    -- Event day the arrival belongs to, mirroring attendance_logs.attendance_date.
    -- Written by the client from device time so multi-day events group correctly.
    arrival_date DATE NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Manila')::DATE),
    -- How the arrival came about.
    source TEXT NOT NULL DEFAULT 'Scan'
        CHECK (source IN ('Scan', 'Promoted', 'AutoRegistered')),
    scanner_device TEXT,
    remarks TEXT
);

-- One announced arrival per participant per event day; re-scans are ignored.
CREATE UNIQUE INDEX IF NOT EXISTS principal_arrival_once_per_day
    ON public.principal_arrival_logs(event_id, participant_id, arrival_date);

CREATE INDEX IF NOT EXISTS principal_arrival_logs_event_idx
    ON public.principal_arrival_logs(event_id, arrived_at DESC);

-- Lets the Overview refresh its arrivals panel live.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'principal_arrival_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.principal_arrival_logs;
    END IF;
END $$;
